server:
  port: 8200

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/pineapple/mapper/xml/*.xml

spring:
#  mvc:
#    pathmatch:
#      matching-strategy: ant_path_matcher
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pineapple?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#  redis:
#    host: localhost
#    port: 6379
#    database: 0
#    timeout: 1800000
#    jedis:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 5
#        min-idle: 0

#wechat:
#  mpAppId: wxda97426bcfc3d1c2
#  mpAppSecret: ddfcee281e409528d728a45884f1ac94
#  userInfoUrl: http://ggkt2.vipgz1.91tunnel.com/admin/wechat/userInfo
